[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm ci && npm run build"

[deploy]
startCommand = "cd backend/dist && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
